stickshot:
  y: 100
PlayableZonne:
  start:
    x: 0
    y: 80
    z: 0
    w: world
  end:
    x: 100
    y: 150
    z: 100
    w: world
respawn:
  x1: 0
  y1: 100
  z1: 0
  x2: 0
  y2: 100
  z2: 0
  x3: 0
  y3: 100
  z3: 0
  x4: 0
  y4: 100
  z4: 0
spawn:
  raillon: 20
player:
  min: 6
  max: 16
  maxHealth: 5
tnt:
  canceled: false